[package]
name = "aery_core"
version = "0.1.0"
edition = "2021"

[dependencies]
riven = { version = "2.72", features = ["tracing"] }
thiserror = "2.0"
tracing = "0.1"
time = "0.3"
serde = "1.0"
bitcode = "0.6"
bytes = "1.10"
lz4_flex = { version = "0.11", default-features = false }