[package]
name = "aery_desktop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aery_core = { path = "../core" }
iced = { git = "https://github.com/iced-rs/iced", rev = "751ea77c29f6eb3d00f45f0a04c833a1d03a425c", features = ["image", "advanced", "tokio"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
time = "0.3.29"
image = "0.24.6"
serde_json = "1.0.107"
dotenv = "0.15.0"
